# Lockdown Browser in Windows Sandbox
# https://github.com/gucci-on-fleek/lockdown-browser
# SPDX-License-Identifier: MPL-2.0+
# SPDX-FileCopyrightText: 2020-2025 gucci-on-fleek and Voidless7125
blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/gucci-on-fleek/lockdown-browser/discussions/new?category=feature-requests
    about: Please post feature requests here.

  - name: Questions, Feedback, and General Discussion
    url: https://github.com/gucci-on-fleek/lockdown-browser/discussions
    about: Please post questions and general feedback here.
